### ISSUE TITLE
PyTorch 0.2 compatability

### ISSUE THREAD

**Issue by MaximumEntropy** [facebookresearch/SentEval#12]
I've noticed that a couple of things break when using PyTorch 0.2. Appears to be related to reductions no longer keeping the reduction axis in the new versrion. I can submit a PR if required.

**Comment by aconneau** [comment]
Sure, a PR would be great. I fixed some of it in https://github.com/facebookresearch/SentEval/commit/91f82751add3fea2cafc8afc16dc45ef72127850 already but apparently not all of them. Thanks.

**Comment by MaximumEntropy** [comment]
Apologies. I didn't notice that PR, I was on an older commit. Indeed, those fixes should work.
