### ISSUE TITLE
Add a task to SentEval

### ISSUE THREAD

**Issue by windweller** [facebookresearch/SentEval#13]
Hi,

I'm trying to add a custom sentiment classification task (SplitClassification), very similar to SNLI/SST to `senteval.py`. I simply put a python file on the same level as `snli.py` and `sst.py`, and imported it into `senteval.py`, but what I get is:

```python
Traceback (most recent call last):
  File "examples/infersent.py", line 23, in <module>
    import senteval
  File "/afs/.../SentEval/senteval.py", line 21, in <module>
    from senti import SentiEval
ImportError: cannot import name SentiEval
```

`infersent.py` already appends the path to senteval, and when I dropped my custom SentiEval task, the whole thing works fine. What went wrong?

**Comment by windweller** [comment]
Sorry...after some checking on PYTHONPATH, this problem still exists.

**Comment by aconneau** [comment]
Could you try to 

"pip install git+https://github.com/facebookresearch/SentEval"

and then try to "import senteval" in a python console?

**Comment by windweller** [comment]
@aconneau I realized you guys have updated the folder/package structure, so I pulled the new package structure in and now it's all working :) Thank you for the comment.
