### ISSUE TITLE
Choose the correct version of SkipThought

### ISSUE THREAD

**Issue by windweller** [facebookresearch/SentEval#14]
Hi,

I'm trying to reproduce the skipthought result and use `skipthought.py` file, and I found two repos:

Theano-based (seems like the original model)
https://github.com/ryankiros/skip-thoughts

TF-based
https://github.com/tensorflow/models/tree/master/skip_thoughts

May I ask which model is used to produce the paper result? And have people attempted the TF model?

**Comment by aconneau** [comment]
Hi,

the skipthought.py was designed for the theano-based skipthought model.
Though, if you prefer TensorFlow, I guess you just need to make skipthought work in your case (meaning making the model take text as input and output embeddings) and then plug it into the "batcher" function.

The InferSent paper's results about SkipThought are directly taken from the Layer Normalization paper of Lei Ba et al. I guess you should be able to replicate their results on SentEval using their sentence encoder.
