### ISSUE TITLE
`byte` type sentences fed in for SNLI task

### ISSUE THREAD

**Issue by kaniblu** [facebookresearch/SentEval#15]
The source of the problem is that there is a line in `loadFile` that encodes `str` to `bytes`. I suppose that the original author intended to convert sentence encodings from `latin-1` to `utf-8`, but `codecs` already does that for us, so `.encode('utf-8')` is unnecessary and might even cause further errors when the user performs string operations on the object.

I have made a pull request on the simple fix.

**Comment by aconneau** [comment]
Thanks! Solved in https://github.com/facebookresearch/SentEval/commit/77755a190ce6c081fcc843fdca25864b67de60a1
