### ISSUE TITLE
ImageCaptionRetrieval - unable to reproduce results in paper

### ISSUE THREAD

**Issue by lajanugen** [facebookresearch/SentEval#19]
I am unable to reproduce the results in the paper for the ImageCaptionRetrieval task. 

I tried the scripts skipthought.py and infersent.py in the examples folder, setting the appropriate paths. I get very poor test scores, close to random. Here's the output for the Infersent model:

Test scores | Image to text:             0.08, 0.34, 0.84, 1058.8
Test scores | Text to image:             0.076, 0.372, 0.848, 509.0

**Comment by aconneau** [comment]
Hi, thanks for noticing this. That's a bug, probably introduced by the recent change to the new pytorch version. I'll look into that ASAP.

**Comment by lajanugen** [comment]
I tried reverting back to the old version in the diff and running with pytorch 0.12. Didn't have any luck there, got  a similar result..

**Comment by aconneau** [comment]
Sorry for taking so long to fix this. Bug introduced in https://github.com/facebookresearch/SentEval/commit/89b8ae52d7695aee9b0e730cdd196a5deb1ada6c . Now fixed.

**Comment by lajanugen** [comment]
Thank you for the fix!
