### ISSUE TITLE
cabextract: command not found

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/SentEval#2]
I did this on `Ubuntu16.04LTS`

```
git clone https://github.com/facebookresearch/SentEval
cd SentEval/
cd data/
./get_transfer_data.bash
...
./get_transfer_data.bash: line 194: cabextract: command not found
cat: senteval_data/MRPC/_2DEC3DBE877E4DB192D17C0256E90F1D: No such file or directory
cat: senteval_data/MRPC/_D7B391F9EAFF4B1B8BCE8F21B20B1B61: No such file or directory
rm: cannot remove 'senteval_data/MRPC/_*': No such file or directory
```

**Comment by loretoparisi** [comment]
**[UPDATE]**

I have solved the first issue doing on `Ubuntu16.04 LTS`:

```
sudo apt-get install cabextract
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
By the way, I have created a `gist` that install all dependecies, run the download scripts, and the tasks.

https://gist.github.com/loretoparisi/9311328876526f37f4893de3c293bd46

**Comment by aconneau** [comment]
Hey, thanks for using SentEval! Great that you solved the problem.
Yes indeed cabextract is needed to extract the MSI files from MRPC.
Note that we mentionned the installation of cabextract in the "Download" section of the README, you may have missed it :).
The problem (and the reason why I didn't include the installation of cabextract in the .bash file) is that "sudo apt-get install cabextract" will not work for CentOS (where you need "yum"). Plus, some users may need to "sudo", which I didn't want to insert in the bash script.

**Comment by aconneau** [comment]
solved

**Comment by loretoparisi** [comment]
@aconneau right! another problem is that to install `conda` you need to accept T&C manually, so that if you launch the gist I have pasted you need some interaction. I do not know a way to install `conda` silently i.e. with no prompt at this time.

**Comment by loicbarrault** [comment]
@loretoparisi `conda` is the working environment, I don't consider it as a dependency. Then it should be installed correctly before. Plus, you might want to run InferSent in a specific environment as well.

**Comment by loretoparisi** [comment]
well that is true.
