### ISSUE TITLE
AssertionError: torch.cuda required for Relatedness

### ISSUE THREAD

**Issue by ShivaliGoel** [facebookresearch/SentEval#21]
While running bow.py for STS Benchmark i get this error:
AssertionError: torch.cuda required for Relatedness

**Comment by aconneau** [comment]
The assertion is : 

`assert torch.cuda.is_available(), 'torch.cuda required for Relatedness'`

It means you don't have torch.cuda available, and SentEval requires that you have torch.cuda (so a gpu) for some tasks (as listed in the README). If you don't have a GPU, you can just remove the tasks that need a GPU from the transfer_tasks list and evaluate on the others (most of the tasks can be run on CPU).
