### ISSUE TITLE
STS13 misses SMT set

### ISSUE THREAD

**Issue by tscheepers** [facebookresearch/SentEval#22]
STS13 should also reference the SMT dataset. This misses from the code.

https://github.com/facebookresearch/SentEval/blob/e97d86198bdf9531f10725e5d124856f7a48de10/senteval/sts.py#L124

The data directory does contain the files.

<img width="592" alt="schermafbeelding 2017-10-23 om 15 29 57" src="https://user-images.githubusercontent.com/44893/31891565-111c2ac8-b807-11e7-958e-5721e2f102a8.png">

**Comment by tscheepers** [comment]
Never mind, license issue

**Comment by aconneau** [comment]
@tscheepers : thanks for noticing this. There is indeed a license issue. I was told (by SemEval POCs) that researchers are still encouraged to publish on STS13 without the SMT (just need to specify it).
