### ISSUE TITLE
skipthought example script

### ISSUE THREAD

**Issue by emanjavacas** [facebookresearch/SentEval#27]
I am having trouble running this:
https://github.com/facebookresearch/SentEval/blob/906b34ae5ffbe17a6970947d5dd5e500ff6daf59/examples/skipthought.py#L51

what version of python actually allows to set attributes of dictionaries like this?

**Comment by aconneau** [comment]
When passed to the SentEval class as a parameter, the object params_senteval is transformed through the "dotdict" function in senteval/utils.py (https://github.com/facebookresearch/SentEval/blob/master/senteval/utils.py#L42-L46).

Which version of python are you using?

**Comment by emanjavacas** [comment]
I had seen that dot dict before, but in that skipthought script the line:

```python
params_senteval.encoder = skipthoughts.load_model()
```

is executed before calling:

```python 
se = senteval.engine.SE(params_senteval, batcher, prepare)
```

So I don't see why it would work...

**Comment by aconneau** [comment]
Closing this issue, feel free to re-open if you still have a problem with this! Thanks
