### ISSUE TITLE
MRPC dataset download bash error/ code error

### ISSUE THREAD

**Issue by gitathrun** [facebookresearch/SentEval#29]
Hi, 
When I am running evaluation by using MRPC dataset, it got two problem:
1. when I use the bash cmd to download the MRPC dataset, at end it shows:
```
./get_transfer_data.bash: line 244: cabextract: command not found
cat: senteval_data/MRPC/_2DEC3DBE877E4DB192D17C0256E90F1D: No such file or directory
cat: senteval_data/MRPC/_D7B391F9EAFF4B1B8BCE8F21B20B1B61: No such file or directory
rm: cannot remove 'senteval_data/MRPC/_*': No such file or directory
```
it turns out the two files in /sentevaldata/MRPC are both empty files.

2. When it runs it throws the error
```
2018-04-20 15:25:36,263 : ***** Transfer task : MRPC *****


2018-04-20 15:25:36,264 : Computing embedding for test
Traceback (most recent call last):
  File "snm_senteval_dsvm_gpu.py", line 66, in <module>
    results = se.eval(transfer_tasks)
  File "../senteval/engine.py", line 56, in eval
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 56, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "../senteval/engine.py", line 94, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "../senteval/mrpc.py", line 76, in run
___mrpc_embed[key][txt_type] = np.vstack(mrpc_embed[key][txt_type])___
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```
I checked the source code in mrpc.py line 76, it seems not the correct way of using np.vstack according to [numpy.vstack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)

Any idea about this error?

Many thanks

**Comment by gitathrun** [comment]
I guess it is a similar issue with #23 ?
Any solutions?

**Comment by gitathrun** [comment]
For other people got the same issue, I think this might works.

For Windows user, you can go to website as SentEval repo provides: https://aclweb.org/aclwiki/Paraphrase_Identification_(State_of_the_art)
and click the first link that download the .msi installer directly from Microsoft website, install it and copy and paste the two files:
1. msr_paraphrase_test.txt
2. msr_paraphrase_train.txt 
into the senteval_data/MRPC/ directory in SentEval repo.

For Linux user, I have attached this two files here, you can download them and replace the files in enteval_data/MRPC/ directory
[msr_paraphrase_test.txt](https://github.com/facebookresearch/SentEval/files/1937795/msr_paraphrase_test.txt)
[msr_paraphrase_train.txt](https://github.com/facebookresearch/SentEval/files/1937796/msr_paraphrase_train.txt)

Tested on both my local laptop and virtual machine in the cloud, it works fine now.

**Comment by aconneau** [comment]
Hi,

as mentioned in the README, for downloading MRPC, you need the "cabextract" Linux command.

Thanks,
Alexis

**Comment by aconneau** [comment]
The new download script should have fixed this issue:
https://github.com/facebookresearch/SentEval/blob/master/data/downstream/get_transfer_data.bash

**Comment by aconneau** [comment]
TODO: Add comprehensive asserts when data hasn't been downloaded properly
These lines:
https://github.com/facebookresearch/SentEval/blob/master/senteval/mrpc.py#L27-L30
should have raised an issue.

**Comment by aconneau** [comment]
Will improve the data download file.
