### ISSUE TITLE
Problem with Padding in BLSTMEncoder and equal length inputs

### ISSUE THREAD

**Issue by rasoolfa** [facebookresearch/SentEval#35]
Hi,

Since it is possible that equal length sentences appear as an input in [1] and np.sort/np.argsort use quicksort by default which is an **unstable** sorting algorithm, shouldn't quicksort function calls in #L45 and #L46 be replaced by mergesort so the input and output have same order for equal keys?

Changed to follwoings:
```
sent_len, idx_sort = np.sort(sent_len, kind='mergesort')[::-1], np.argsort(-sent_len, kind='mergesort')
idx_unsort = np.argsort(idx_sort, kind='mergesort')
```

[1] https://github.com/facebookresearch/SentEval/blob/master/examples/models.py#L44

**Comment by aconneau** [comment]
Hi,
I think in that particular case it shouldn't be a problem and input and output should have same order for equal keys. Could you provide an example where using this method leads to a bad re-sorting?
Thanks,
Alexis

**Comment by aconneau** [comment]
Closing this issue, please feel free to re-open anytime to follow up on this!

**Comment by Tsegaye-misikir** [comment]
I was trying to access the file but the directory is not the path provided.
https://github.com/facebookresearch/SentEval/blob/master/examples/models.py

where should I get it?
