### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by tscheepers** [facebookresearch/SentEval#4]
I'm currently incorporating SentEval in my training procedure, so it evaluates intermediate model parameters every `x` training steps. However I'm now finding myself hacking the code to make it work with Python 3.6, which I need for other components in my model. It would be wonderful if SentEval had out of the box support for Python 3.x.

**Comment by aconneau** [comment]
Can you list the bugs you faced to make it easier for us to fix it and make SentEval python 3.x compatible? We also welcome PRs.

**Comment by tscheepers** [comment]
PR #5 submitted 😁
