### ISSUE TITLE
Transfer Performance on MRPC dataset is slight low than reported

### ISSUE THREAD

**Issue by JinmingZhao** [facebookresearch/SentEval#43]
As is shown in https://github.com/facebookresearch/InferSent， the MRPC result is 76.2/83.1 based on the released inferent1 model， but my result is 74.14/82.06， and my parameter setting as below：
params_senteval = {'task_path': '/data3/zjm/dataset/MSRParaphraseCorpus', 'usepytorch': True, 'kfold': 10}
params_senteval['classifier'] = {'nhid': 512, 'optim': 'adam', 'batch_size': 128,
                                 'tenacity': 3, 'epoch_size': 2}
{u'acc': 74.14, u'f1': 82.06, u'ntest': 1725, u'devacc': 75.370000000000005, u'ndev': 4076}

Could you provide the default setting for MRPC dataset？

Thank you very much！

**Comment by aconneau** [comment]
Hi,

please use the best setting as specified in the README, that is:

params = {'task_path': PATH_TO_DATA, 'usepytorch': True, 'kfold': 10}
params['classifier'] = {'nhid': 0, 'optim': 'adam', 'batch_size': 64,
                                 'tenacity': 5, 'epoch_size': 4}

Thanks
