### ISSUE TITLE
Incomplete dataset(MR,SUBJ,SICK-E)

### ISSUE THREAD

**Issue by ChenXi1992** [facebookresearch/SentEval#63]
Part of the dataset that I download is not complete: 

The MR dataset that I download only contains 74 sentences instead of 11K, also SUBJ only contain 5020 instead of  10K, same for SICK-E and SICK-MSE. 

I also downloaded the dataset by the link at Readme, The SUBJ dataset only contains 5020 instead of 10K. 

Can somebody take a look? Thanks.

**Comment by Punchwes** [comment]
I wonder how you got this solved? I also got incomplete dataset for a lot of them

**Comment by ChenXi1992** [comment]
> I wonder how you got this solved? I also got incomplete dataset for a lot of them

It's been a long time..  it's the operation system  in my case if I remembered correctly..   I tried different operation system(Linux, Ubuntu ), one of it works.
