### ISSUE TITLE
No score in STS15

### ISSUE THREAD

**Issue by sh0416** [facebookresearch/SentEval#85]
Hi, I am curious about the dataset STS15.

In STS15, some rows doesn't have score and the code ignores these examples.

* Is there any reason that the lines exists?
* I think the dataset statistics is inappropriate if we ignored. Could you correct it?

**Comment by noooob-coder** [comment]
I also encountered this problem recently. Have you solved it？

**Comment by sh0416** [comment]
@noooob-coder 
I followed the process that they took.

Just remove the rows that are not completed.

In my case, I think the reason that the statistic is unfair when we compare the evaluated result with the statistics that some papers reported, which is not mentioned about these details.

So, I just evaluate other methods on the same framework.
